### ISSUE TITLE
Slider not working on mobile

### ISSUE THREAD

**Issue by itsmichaeldiego** [dmitrymorozoff/react-circle-slider#7]
Hey! Thank you very much for the library.

I've tried to test the circle slider in mobile, but it does not work on my end, it just moves the page! 

I guess the touch event is not allowed for mobile?

Here is a quick video:
![ezgif-1-d7cf483683d0](https://user-images.githubusercontent.com/6419886/48562624-e5353800-e8f2-11e8-8a88-97dbfffeb7a4.gif)

**Comment by dmitrymorozoff** [comment]
Hey. Thank you for the feedback. Yes, it's a bug. I will fix it soon.

**Comment by dmitrymorozoff** [comment]
@itsmichaeldiego  If you want, you can do pull request.

**Comment by dmitrymorozoff** [comment]
@itsmichaeldiego Not. Now there is no such functionality. But I will add it in the future.

**Comment by itsmichaeldiego** [comment]
@dmitrymorozoff I could help you develop it between today and tomorrow if you point me on the right direction

**Comment by bastiion** [comment]
I'm not sure, whether this should be solved within the component itself or in the context of using this element. Wrapping the element in an `inline-block` element , which is styled using `touch-action: none` does the job on most browsers. On Safari and iOS another workaround is necessary: [prevent scroll for modals in iOS](https://benfrain.com/preventing-body-scroll-for-modals-in-ios/)

**Comment by erpardeepjain** [comment]
@dmitrymorozoff any update on Mobile working? Still not working on Mobile devices properly.
